theme: "PaperMod"
baseURL: "https://yuiwa-TK.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Yuta Iwatani
paginate: 5

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
                  category: categories
                  tag: tags
                  series: series
        menu:
            main:
                - name: Research
                  url : research/
                  weight: 10
                - name: CV
                  url : cv/
                  weight: 11
                - name: Study Notes
                  url : studynotes/
                  weight: 12
                # - name: Search
                #   url: search/
                #   weight: 10
                - name: Archives
                  url: archives
                  weight: 20
                - name: Tags
                  url: tags/
                  weight: 30
    jp:
        languageName: "Japanese"
        weight: 2
        taxonomies:

params:
    homeInfoParams:
        Title: Welcome 🛩 🌊
        Content: Yuta Iwatani is a PhD student at [Tohoku University](https://www.klab.mech.tohoku.ac.jp/index_jpn.html) in Japan, specializing in aerospace engineering.
                 I am also honored to hold the JSPS Research Fellowship for Young Scientists (DC1).
                 My research interests lie in the field of Computational Fluid Dynamics (CFD) and Data Science for CFD data, with a focus on compressible flows. 
                 Please visit [Research]() to dive into my current and past research projects.
                 Please do not hesitate to contact me if you have any questions on my codes and my study notes. 
    defaultTheme: light #dark / auto

    socialIcons:
        - name: github
          url: "https://github.com/yuiwa-TK"
        - name: googlescholar
          url: "https://scholar.google.co.jp/citations?hl=ja&user=PkjX1xAAAAAJ"
        - name: twitter
          url: "https://twitter.com/WantanCFD"