theme: "PaperMod"
baseURL: "https://yuiwa-TK.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Yuta Iwatani
paginate: 5

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
                  category: categories
                  tag: tags
                  series: series
        menu:
            main:
                - name: Research
                  url : research_project/
                  weight: 10
                - name: Publications
                  url: publications/
                  weight: 1
                - name: CV
                  url : cv/
                  weight: 11
                - name: Study Note
                  url : studynotes/
                  weight: 12
                # - name: Search
                #   url: search/
                #   weight: 10
                - name: Archive
                  url: archives
                  weight: 20
                - name: Tag
                  url: tags/
                  weight: 30
    # jp:
    #     languageName: "Japanese"
    #     weight: 2
    #     taxonomies:
    #               category: categories
    #               tag: tags
    #               series: series
    #     menu:
    #       main:
    #         - name: Research
    #           url : research2/
    #           weight: 10
    #         - name: CV
    #           url : cv/
    #           weight: 11
    #         - name: Study Note
    #           url : studynotes/
    #           weight: 12

params:
    homeInfoParams:
        Title: Yuta Iwatani
        Content: I am a third-year Ph.D. student [Aerodynamic Design Research Group](https://www.klab.mech.tohoku.ac.jp/index.html) at [Tohoku University](https://www.tohoku.ac.jp/en/).
        My current research numerically investigates how wall temperature affects boundary layer transition in the transonic regime, which is crucial for improving the efficiency and safety of high-speed aircraft. 
        Beyond this, I am also developing advanced analysis methods, specifically based on resolvent analysis, to better understand and control intricate flow dynamics.
        Currently, I am awarded by the [JSPS (Japan Society for the Promotion of Science) Research Fellowship for Young Scientists (DC1)](https://www.jsps.go.jp/english/e-pd/). 
        {{< figure align=center src="./Re300.png" >}} 
        Feel free to contact me: **yuta.iwatani(at)dc.tohoku.ac.jp** 
    defaultTheme: light #dark / auto

    socialIcons:
        - name: github
          url: "https://github.com/yuiwa-TK"
        - name: googlescholar
          url: "https://scholar.google.co.jp/citations?hl=ja&user=PkjX1xAAAAAJ"
        # - name: twitter
        #   url: "https://twitter.com/WantanCFD"


# for search page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary